apiVersion: v1
kind: Service
metadata:
  name: bookshop
  namespace: bookshop
spec:
  selector:
    app: bookshop
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
